### ISSUE TITLE
Erreur d'encodage ?

### ISSUE THREAD

**Issue by Freyj** [Heartbroken-Git/TFP_CORE#26]
Notamment sur les noms de fichiers dans le config.cpp de la musique, y a des caractères chelous (cf le lien) 
https://github.com/Heartbroken-Git/TFP_CORE/blob/cdc4dcd71d7f14b54ce806992f88133104eaa53c/TFP_Music/config.cpp#L41

**Comment by Heartbroken-Git** [comment]
Effectivement, ça m'a tout l'air d'être une conversion de merde entre l'ANSI et l'UTF-8 ou vice-versa. :thinking: 

Est-ce que tu peux vérifier en jeu (avec une mission vierge sur la Réalité Virtuelle par exemple avec juste un joueur Zeus, en posant le module musique de Zeus) si les musiques concernées sont jouées par le jeu ou si ça merde ?

**Comment by Freyj** [comment]
l'ANSI c'est du caca ! 
Je vais voir ça.

**Comment by Freyj** [comment]
Tous ceux avec un accent ne sont pas joués. Il fait bien la conversion en affichage en lettre sans accent mais ça ne joue pas le morceau. Et j'ai l'impression qu'avec un - non plus. Le _ dans le nom de fichier ça passe, le - non.

**Comment by Heartbroken-Git** [comment]
Rah mais merde ça marchait très bien avant.
Le week-end prochain je regarderais pour regler ça dans un hotfix. Il y a
d'autres fichiers impactés que les musiques ?

**Comment by Freyj** [comment]
Euh j'ai rien vu d'impacté autre mais j'ai pas tout parcouru

**Comment by Heartbroken-Git** [comment]
@Freyj Je te laisse jeter un coup d’œil dans la PR #27, normalement j'ai corrigé tous les morceaux qui déconnaient.
