### ISSUE TITLE
Ajout de gilets et tenues du GIGN

### ISSUE THREAD

**Issue by Heartbroken-Git** [Heartbroken-Git/TFP_CORE#57]
A la demande de @Freyj il faudrait ajouter des gilets et tenues du GIGN en plus des gilets de la Gendarmerie Nationale déjà présents dans le mod.

- [x] Ajout des gilets
  - [x] GIGN
    - [x] Retexture du Gilet d'assaut avec la sérigraphie "GIGN" en blanc sur noir
    - [x] Retexture du Gilet d'assaut lourd avec la sérigraphie "GIGN" en blanc sur noir
    - [x] Retexture du Gilet d'assaut lourd de l'OTAN avec la sérigraphie "GIGN" en blanc sur noir avant/arrière + épaules
      - [x] Variante Spéciale
      - [x] Variante Grenadier
  - [x] AGIGN
    - [x] Retexture du Gilet d'assaut avec "AGIGN" en blanc sur noir
    - [x] Retexture du Gilet d'assaut lourd avec "AGIGN" en blanc sur noir
    - [x] Ajout du nouveau patch des AGIGN
- [x] Tester s'il est possible de modifier la tenue tankiste AAF en tenue GIGN
- [x] Retexturer la tenue tankiste de l'AAF en tenue GIGN

**Comment by Freyj** [comment]
Quid d'un patch du GIGN ? °o°

**Comment by Heartbroken-Git** [comment]
On en avait déjà plusieurs dans les multiples mods de patch sur le modpack.
Néanmoins je suis pas sur de pouvoir vérifier (charger tout le modpack
c'est peut-être pas une bonne idée xD).
Du coup si tu veux tu peux vérifier sur les modpacks contemporain
principalement s'il y a déjà des patch du GIGN et s'ils sont satisfaisants.
Quant aux AGIGN j'ai l'ancien modèle de patch dans le modpack déjà. Je sais
pas si mettre le nouveau est pertinent car j'ai déjà un doute de si vous
jouerez une AGIGN xD

**Comment by Heartbroken-Git** [comment]
@Freyj Théoriquement la tenue de tankiste de l'AAF semble bien retexturable. Par contre pas de templates à ma connaissance. Je verrais ce que je pourrais faire :)

**Comment by Heartbroken-Git** [comment]
Gilets et tenue intégrés dans la `indev5.1` par le commit 5003b8d457bfface1c1996023321d065c2370e9b.
Fermeture de l'issue.
